# modified by evgeniikosarev

name: Build and Publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t evgeniikosarev/application_images:latest .
          docker push evgeniikosarev/application_images:latest