# modified by evgeniikosarev

name: Build and Publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build and push image
        run: |
          docker build -t evgeniikosarev/application_images:latest .
          docker push evgeniikosarev/application_images:latest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: kubectl

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: cluster-for-evgenii-app
          location: europe-west1
          project_id: clgcporg10-190

      - name: update image
        run: |
          kubectl set image deployment/evgenii-app-depl evgenii-app-container=evgeniikosarev/application_images:latest
